steps:
  - id: Build container image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
      - .

  - id: Push container image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "3000"
      - --cpu
      - "1"
      - --memory
      - 1Gi
      - --max-instances
      - "20"
      - --min-instances
      - "0"
      - --set-env-vars=NEXTAUTH_URL=https://www.eventsslot.com,NEXTAUTH_URL_INTERNAL=http://localhost:3000,NEXT_PUBLIC_APP_URL=https://www.eventsslot.com,EMAIL_PROVIDER=smtp,RESEND_FROM=EventSlot\ <hello@eventsslot.com>
      - --update-secrets=DATABASE_URL=EVENTSLOT_DATABASE_URL:latest,DIRECT_URL=EVENTSLOT_DIRECT_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,GOOGLE_CLIENT_ID=EVENTSLOT_GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=EVENTSLOT_GOOGLE_CLIENT_SECRET:latest,RESEND_API_KEY=RESEND_API_KEY:latest,SMTP_HOST=SMTP_HOST:latest,SMTP_PORT=SMTP_PORT:latest,SMTP_SECURE=SMTP_SECURE:latest,SMTP_USER=SMTP_USER:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,SMTP_FROM=SMTP_FROM:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,CRON_SECRET=CRON_SECRET:latest,R2_ACCOUNT_ID=CLOUDFLARE_R2_ACCOUNT_ID:latest,R2_ACCESS_KEY_ID=CLOUDFLARE_R2_ACCESS_KEY_ID:latest,R2_SECRET_ACCESS_KEY=CLOUDFLARE_R2_SECRET_ACCESS_KEY:latest,R2_BUCKET_NAME=CLOUDFLARE_R2_BUCKET_NAME:latest,SUPER_ADMIN_EMAIL=SUPER_ADMIN_EMAIL:latest,SUPER_ADMIN_EMAIL_2=SUPER_ADMIN_EMAIL_2:latest,PAYSTACK_SECRET_KEY=PAYSTACK_SECRET_KEY:latest,GROQ_API_KEY=GROQ_API_KEY:latest,OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,R2_PUBLIC_URL=CLOUDFLARE_R2_PUBLIC_URL:latest,ENCRYPTION_KEY=ENCRYPTION_KEY:latest,QR_SECRET=QR_SECRET:latest

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}

substitutions:
  _SERVICE: eventslot-web
  _REGION: us-central1
  _REPOSITORY: eventslot
  _IMAGE_TAG: manual

options:
  logging: CLOUD_LOGGING_ONLY
