ALTER TABLE "TicketTier"
ADD COLUMN "presetKey" TEXT,
ADD COLUMN "badgeColor" TEXT NOT NULL DEFAULT '#A8A9AD',
ADD COLUMN "textColor" TEXT NOT NULL DEFAULT '#1A1A1A',
ADD COLUMN "metallic" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "prestige" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'KES';
