ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "paymentPinHash" TEXT,
ADD COLUMN IF NOT EXISTS "paymentPinEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "paymentPinUpdatedAt" TIMESTAMP(3);
