export type TutorialStep = {
  id: string
  sectionId: string
  title: string
  description: string
  target: string
  position: "top" | "bottom" | "left" | "right" | "center"
  action?: string
  actionRoute?: string
  icon: string
  spotlight: boolean
}

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: "welcome",
    sectionId: "dashboard",
    title: "Welcome to EventSlot! 🎉",
    description: "You're now set up to manage events like a pro. Let us show you around in under 2 minutes.",
    target: "body",
    position: "center",
    icon: "👋",
    spotlight: false,
  },
  {
    id: "dashboard_overview",
    sectionId: "dashboard",
    title: "Your Command Center",
    description: "This is your dashboard. At a glance you can see total events, registrations, waitlist count, and recent activity.",
    target: '[data-tutorial="dashboard-stats"]',
    position: "bottom",
    icon: "📊",
    spotlight: true,
  },
  {
    id: "create_event",
    sectionId: "create",
    title: "Create Event Entry Point",
    description: "This button opens the event creation flow where you set title, date, location, capacity, and registration questions.",
    target: '[data-tutorial="create-event-btn"]',
    position: "bottom",
    icon: "✨",
    spotlight: true,
  },
  {
    id: "my_events",
    sectionId: "dashboard_event",
    title: "Manage Your Events",
    description: "All your events live here. See who registered, who's on the waitlist, and manage everything from one place.",
    target: '[data-tutorial="my-events-nav"]',
    position: "right",
    icon: "📅",
    spotlight: true,
  },
  {
    id: "registration_link",
    sectionId: "registration",
    title: "Share Your Registration Link",
    description: "Every event gets a unique link. Share it on WhatsApp, email, or anywhere — attendees register without creating an account.",
    target: '[data-tutorial="event-link"]',
    position: "top",
    icon: "🔗",
    spotlight: true,
  },
  {
    id: "waitlist",
    sectionId: "dashboard_event",
    title: "Automatic Waitlist Management",
    description: "When slots fill up, EventSlot automatically puts people on a waitlist. If someone cancels, the next person is confirmed automatically.",
    target: '[data-tutorial="waitlist-section"]',
    position: "top",
    icon: "⚡",
    spotlight: true,
  },
  {
    id: "confirm_attendance",
    sectionId: "registration",
    title: "Attendee Self-Check",
    description: "Attendees can confirm their attendance and download their QR ticket anytime — no login needed.",
    target: '[data-tutorial="confirm-attendance"]',
    position: "top",
    icon: "🎟️",
    spotlight: true,
  },
  {
    id: "notifications",
    sectionId: "dashboard",
    title: "Stay in the Loop",
    description: "Notifications alert you when someone registers, joins the waitlist, or when a slot opens up.",
    target: '[data-tutorial="notifications-nav"]',
    position: "right",
    icon: "🔔",
    spotlight: true,
  },
  {
    id: "analytics_insights",
    sectionId: "analytics",
    title: "Analytics & AI Insights",
    description: "Use Insights to understand attendance patterns, trends, and AI-generated recommendations for improving turnout.",
    target: '[data-tutorial="insights-nav"]',
    position: "right",
    icon: "📈",
    spotlight: true,
  },
  {
    id: "report_generation",
    sectionId: "report",
    title: "Generate Event Reports",
    description: "Open an event to generate and download a stakeholder-ready report with metrics, findings, and recommendations.",
    target: '[data-tutorial="my-events-nav"]',
    position: "right",
    icon: "📝",
    spotlight: true,
  },
  {
    id: "team_members",
    sectionId: "team",
    title: "Invite Team Members",
    description: "Add collaborators so they can help manage events, attendee lists, and operations without sharing your account.",
    target: '[data-tutorial="team-nav"]',
    position: "right",
    icon: "👥",
    spotlight: true,
  },
  {
    id: "community_invite",
    sectionId: "community",
    title: "Share Invite, Earn Tokens",
    description: "Open Community and tap Share Invite to send your referral link. You earn tokens when invited users sign up and create events.",
    target: '[data-tutorial="community-share-invite"]',
    position: "top",
    icon: "📣",
    spotlight: true,
  },
  {
    id: "profile",
    sectionId: "dashboard",
    title: "Complete Your Profile",
    description: "Add your organization name and photo so attendees recognize your events. It builds trust.",
    target: '[data-tutorial="profile-nav"]',
    position: "right",
    icon: "👤",
    spotlight: true,
  },
  {
    id: "complete",
    sectionId: "dashboard",
    title: "You're All Set! 🚀",
    description: "That's everything you need to know. You can continue exploring freely and start creating events whenever you're ready.",
    target: "body",
    position: "center",
    icon: "🎯",
    spotlight: false,
  },
]
