from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


OUTPUT = Path("EventSlot_WalkIn_Share_Card_Review_2026-08-07.docx")


def set_font(run, name: str, size: int, bold: bool = False, color: tuple[int, int, int] | None = None):
    run.font.name = name
    run._element.rPr.rFonts.set(qn("w:ascii"), name)
    run._element.rPr.rFonts.set(qn("w:hAnsi"), name)
    run.font.size = Pt(size)
    run.bold = bold
    if color:
        run.font.color.rgb = RGBColor(*color)


def set_paragraph_spacing(paragraph, before=0, after=0, line=1.15):
    fmt = paragraph.paragraph_format
    fmt.space_before = Pt(before)
    fmt.space_after = Pt(after)
    fmt.line_spacing = line


def shade_cell(cell, fill: str):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def set_page(section):
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)


def add_title(doc: Document):
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_paragraph_spacing(title, after=4, line=1.0)
    run = title.add_run("EventSlot Walk-In Share Card Review")
    set_font(run, "Calibri", 22, bold=True, color=(46, 116, 181))

    meta = doc.add_paragraph()
    set_paragraph_spacing(meta, after=10)
    run = meta.add_run("Prepared on Friday, August 7, 2026")
    set_font(run, "Calibri", 10, color=(89, 89, 89))

    intro = doc.add_paragraph()
    set_paragraph_spacing(intro, after=10, line=1.15)
    intro_run = intro.add_run(
        "This review covers the current walk-in share card generated by EventSlot, "
        "what is already working well, and the highest-value improvements that would make the card more useful for social sharing, event memory, and event-day trust."
    )
    set_font(intro_run, "Calibri", 11, color=(31, 37, 41))


def add_heading(doc: Document, text: str, level: int = 1):
    paragraph = doc.add_paragraph()
    set_paragraph_spacing(paragraph, before=12 if level == 1 else 8, after=6)
    run = paragraph.add_run(text)
    if level == 1:
        set_font(run, "Calibri", 16, bold=True, color=(46, 116, 181))
    else:
        set_font(run, "Calibri", 13, bold=True, color=(31, 77, 120))


def add_bullets(doc: Document, items: list[str]):
    for item in items:
        paragraph = doc.add_paragraph(style="List Bullet")
        set_paragraph_spacing(paragraph, after=4, line=1.15)
        run = paragraph.add_run(item)
        set_font(run, "Calibri", 11, color=(31, 37, 41))


def add_priority_table(doc: Document):
    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    table.autofit = False
    widths = [Inches(1.0), Inches(2.0), Inches(1.3), Inches(2.2)]
    headers = ["Priority", "Improvement", "Impact", "Why it matters"]
    for idx, cell in enumerate(table.rows[0].cells):
        cell.width = widths[idx]
        shade_cell(cell, "F2F4F7")
        paragraph = cell.paragraphs[0]
        set_paragraph_spacing(paragraph, after=0, line=1.0)
        run = paragraph.add_run(headers[idx])
        set_font(run, "Calibri", 10, bold=True, color=(31, 37, 41))

    rows = [
        ("P1", "Show check-in time", "High", "Adds proof and trust for attendees, organisers, and social reposts."),
        ("P1", "Long-title safe layout", "High", "Prevents breakage when event names, locations, or attendee names are longer than the preview example."),
        ("P1", "Venue short label + direction cue", "High", "Makes the card more useful as a real memory and not just a social badge."),
        ("P2", "Theme per event poster", "Medium", "Helps the card feel like the event itself rather than a generic EventSlot template."),
        ("P2", "Story-first export variant", "Medium", "Creates a lighter version optimized for Instagram/WhatsApp status reposts."),
        ("P3", "Organiser logo / host badge option", "Medium", "Improves co-branding for conferences, churches, and partner events."),
    ]

    for row_data in rows:
        row = table.add_row()
        for idx, value in enumerate(row_data):
            row.cells[idx].width = widths[idx]
            paragraph = row.cells[idx].paragraphs[0]
            set_paragraph_spacing(paragraph, after=0, line=1.15)
            run = paragraph.add_run(value)
            set_font(run, "Calibri", 10, color=(31, 37, 41))


def add_callout(doc: Document, text: str):
    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"
    table.autofit = False
    table.columns[0].width = Inches(6.3)
    cell = table.rows[0].cells[0]
    shade_cell(cell, "F4F6F9")
    p = cell.paragraphs[0]
    set_paragraph_spacing(p, after=0, line=1.15)
    run = p.add_run(text)
    set_font(run, "Calibri", 11, bold=True, color=(31, 58, 95))


def build_doc():
    doc = Document()
    set_page(doc.sections[0])

    add_title(doc)

    add_heading(doc, "What Works Well")
    add_bullets(
        doc,
        [
            "The share card already feels celebratory. The 'I WAS HERE' framing and 'CHECKED IN' state create a strong social proof moment.",
            "The poster-first hero area is the right direction. When a real event poster is available, the card naturally becomes more attractive and event-specific.",
            "The card carries the most important attendance proof fields: attendee name, registration number, date context, and venue context.",
            "Multi-day support already exists in the generator. The 'Day X of N' format is a strong base for festivals, camps, and conferences.",
            "The footer CTA keeps EventSlot visible without overwhelming the attendee proof area.",
        ],
    )

    add_heading(doc, "Current Gaps")
    add_bullets(
        doc,
        [
            "The card does not currently show the exact check-in timestamp, which weakens the trust signal for event-day proof and reposting.",
            "Long titles, long attendee names, and longer venue labels need stricter layout protection so the card stays elegant for real-world data.",
            "When poster art is missing, the fallback visual is clean but generic; it does not yet feel clearly tied to the event identity.",
            "The card is strong as a memory artifact, but it can become more useful as a distribution asset by supporting a lighter social-story variant.",
            "The host/event identity could be stronger through optional organiser branding or event-category accents for high-profile events.",
        ],
    )

    add_heading(doc, "Priority Improvements")
    add_priority_table(doc)

    add_heading(doc, "Recommended Product Direction")
    add_bullets(
        doc,
        [
            "Keep the current poster-first composition and celebratory tone. That is the right product direction.",
            "Add a visible 'Checked in at' timestamp plus optional day badge on the cream information card.",
            "Use stronger text wrapping and height rules for the title, attendee name, and venue lines so the layout remains safe with real event data.",
            "Introduce an optional social variant: less detail, larger poster, stronger attendee badge, and a layout optimized for status/story reposting.",
            "Allow each walk-in card to inherit subtle accent colors from the uploaded poster or selected event category so cards feel more premium and less generic.",
        ],
    )

    add_callout(
        doc,
        "Recommendation: keep the existing walk-in card concept, then improve trust markers, text safety, and event-specific personality before expanding into more formats."
    )

    add_heading(doc, "Implementation Notes", level=2)
    add_bullets(
        doc,
        [
            "The current generator already supports poster ingestion, venue fallback, attendee name, registration number, and multi-day labels.",
            "The highest-value next engineering changes are in the SVG composition rules, not the overall architecture.",
            "A small second export variant for story/status would likely create a strong perceived quality gain with limited engineering cost.",
        ],
    )

    doc.save(OUTPUT)


if __name__ == "__main__":
    build_doc()
